# Generated by Django 5.1.3 on 2024-11-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='num_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
