# Generated by Django 5.1.3 on 2024-11-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storeuser_num_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
