# Generated by Django 5.1.3 on 2024-11-30 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
        ('core', '0003_storeuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='store_user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.storeuser'),
            preserve_default=False,
        ),
    ]
