# Generated by Django 5.1.3 on 2024-11-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.IntegerField(default=1)),
                ('description', models.TextField(default='')),
                ('excerpt', models.CharField(default='', max_length=150)),
                ('image', models.ImageField(default='images/default.jpeg', upload_to='images')),
                ('tags', models.ManyToManyField(to='Products.tag')),
            ],
        ),
    ]
