# Generated by Django 4.1.7 on 2023-08-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="excerpt",
        ),
    ]
