# Generated by Django 4.1.7 on 2023-08-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0002_remove_product_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="excerpt",
            field=models.CharField(default="", max_length=150),
        ),
    ]
