# Generated by Django 4.1.7 on 2023-08-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0003_product_excerpt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="excerpt",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
