# Generated by Django 4.1.7 on 2023-08-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0004_remove_product_description_remove_product_excerpt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="excerpt",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=1),
        ),
    ]
