# Generated by Django 4.1.7 on 2023-08-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0005_product_description_product_excerpt_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="images/default.jpeg", upload_to="images"),
        ),
    ]
